// novel-sub/frontend/src/components/PageShell.vue
<template>
  <div class="novel-page">
    <div v-if="title || $slots.extra" class="novel-page-header">
      <h4 v-if="title" class="novel-page-title">{{ title }}</h4>
      <div v-if="$slots.extra" class="novel-page-extra">
        <slot name="extra" />
      </div>
    </div>
    <div class="novel-page-body">
      <slot />
    </div>
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, default: '' },
});
</script>

// novel-sub/frontend/src/components/PageShell.jsx
import { Typography } from 'antd';

export default function PageShell({ title, extra, children }) {
  return (
    <div className="novel-page">
      {(title || extra) && (
        <div className="novel-page-header">
          {title && (
            <Typography.Title level={4} className="novel-page-title">
              {title}
            </Typography.Title>
          )}
          {extra && <div className="novel-page-extra">{extra}</div>}
        </div>
      )}
      <div className="novel-page-body">{children}</div>
    </div>
  );
}
