// novel-sub/frontend/src/views/NovelCreationPage.jsx
import { useState } from 'react';
import { Button, Form, Input, Select, Steps, message } from 'antd';
import { useNavigate } from 'react-router-dom';
import PageShell from '../components/PageShell.jsx';
import { createNovel } from '../services/novelService.js';

const DRAFT_KEY = 'novel:create:draft';

function saveDraft(data) {
  sessionStorage.setItem(DRAFT_KEY, JSON.stringify(data));
}

function loadDraft() {
  try {
    return JSON.parse(sessionStorage.getItem(DRAFT_KEY) || '{}');
  } catch {
    return {};
  }
}

export default function NovelCreationPage() {
  const navigate = useNavigate();
  const [current, setCurrent] = useState(0);
  const [form] = Form.useForm();
  const [draft] = useState(() => loadDraft());

  const steps = [
    { title: '基本信息' },
    { title: '大纲构建' },
    { title: '正文创作' },
    { title: '审稿润色' },
  ];

  const handleNext = async () => {
    const values = await form.validateFields();
    saveDraft({ ...loadDraft(), ...values });
    if (current < steps.length - 1) {
      setCurrent(c => c + 1);
      return;
    }
    try {
      const payload = { ...loadDraft(), ...values };
      await createNovel(payload);
      sessionStorage.removeItem(DRAFT_KEY);
      message.success('小说创建成功');
      navigate('..');
    } catch (e) {
      message.error(e.message || '创建失败');
    }
  };

  return (
    <PageShell title="新建小说">
      <Steps current={current} items={steps} style={{ marginBottom: 24 }} />
      <Form form={form} layout="vertical" initialValues={draft}>
        {current === 0 && (
          <>
            <Form.Item name="title" label="标题" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
            <Form.Item name="author_name" label="作者" rules={[{ required: true }]}>
              <Input />
            </Form.Item>
            <Form.Item name="status" label="状态" initialValue="draft">
              <Select
                options={[
                  { value: 'draft', label: '草稿' },
                  { value: 'published', label: '已发布' },
                ]}
              />
            </Form.Item>
          </>
        )}
        {current === 1 && (
          <Form.Item name={['plot', 'outline']} label="大纲">
            <Input.TextArea rows={8} />
          </Form.Item>
        )}
        {current === 2 && (
          <Form.Item name={['draft', 'content']} label="正文">
            <Input.TextArea rows={12} />
          </Form.Item>
        )}
        {current === 3 && (
          <Form.Item name={['draft', 'review']} label="审稿意见">
            <Input.TextArea rows={8} />
          </Form.Item>
        )}
      </Form>
      <div style={{ marginTop: 16, display: 'flex', gap: 8 }}>
        <Button disabled={current === 0} onClick={() => setCurrent(c => c - 1)}>
          上一步
        </Button>
        <Button type="primary" onClick={handleNext}>
          {current === steps.length - 1 ? '完成' : '下一步'}
        </Button>
      </div>
    </PageShell>
  );
}

// novel-sub/frontend/src/views/NovelCreationPage.vue
<template>
  <PageShell title="新建小说">
    <el-steps :active="current" finish-status="success" style="margin-bottom: 24px">
      <el-step v-for="step in steps" :key="step.title" :title="step.title" />
    </el-steps>

    <el-form ref="formRef" :model="form" label-position="top">
      <template v-if="current === 0">
        <el-form-item label="标题" prop="title" :rules="[{ required: true, message: '请输入标题' }]">
          <el-input v-model="form.title" />
        </el-form-item>
        <el-form-item label="作者" prop="author_name" :rules="[{ required: true, message: '请输入作者' }]">
          <el-input v-model="form.author_name" />
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-select v-model="form.status" style="width: 100%">
            <el-option value="draft" label="草稿" />
            <el-option value="published" label="已发布" />
          </el-select>
        </el-form-item>
      </template>
      <template v-else-if="current === 1">
        <el-form-item label="大纲">
          <el-input v-model="form.plot.outline" type="textarea" :rows="8" />
        </el-form-item>
      </template>
      <template v-else-if="current === 2">
        <el-form-item label="正文">
          <el-input v-model="form.draft.content" type="textarea" :rows="12" />
        </el-form-item>
      </template>
      <template v-else-if="current === 3">
        <el-form-item label="审稿意见">
          <el-input v-model="form.draft.review" type="textarea" :rows="8" />
        </el-form-item>
      </template>
    </el-form>

    <div style="margin-top: 16px; display: flex; gap: 8px">
      <el-button :disabled="current === 0" @click="current -= 1">上一步</el-button>
      <el-button type="primary" @click="handleNext">
        {{ current === steps.length - 1 ? '完成' : '下一步' }}
      </el-button>
    </div>
  </PageShell>
</template>

<script setup>
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import PageShell from '../components/PageShell.vue';
import { createNovel } from '../services/novelService.js';

const DRAFT_KEY = 'novel:create:draft';

function saveDraft(data) {
  sessionStorage.setItem(DRAFT_KEY, JSON.stringify(data));
}

function loadDraft() {
  try {
    return JSON.parse(sessionStorage.getItem(DRAFT_KEY) || '{}');
  } catch {
    return {};
  }
}

const router = useRouter();
const current = ref(0);
const formRef = ref(null);
const steps = [
  { title: '基本信息' },
  { title: '大纲构建' },
  { title: '正文创作' },
  { title: '审稿润色' },
];

const draft = loadDraft();
const form = reactive({
  title: draft.title || '',
  author_name: draft.author_name || '',
  status: draft.status || 'draft',
  plot: { outline: draft.plot?.outline || '' },
  draft: {
    content: draft.draft?.content || '',
    review: draft.draft?.review || '',
  },
});

async function handleNext() {
  const valid = await formRef.value?.validate().catch(() => false);
  if (!valid) return;

  saveDraft({ ...loadDraft(), ...form });
  if (current.value < steps.length - 1) {
    current.value += 1;
    return;
  }

  try {
    const payload = { ...loadDraft(), ...form };
    await createNovel(payload);
    sessionStorage.removeItem(DRAFT_KEY);
    ElMessage.success('小说创建成功');
    router.push({ name: 'novel-list' });
  } catch (e) {
    ElMessage.error(e.message || '创建失败');
  }
}
</script>
