// menu-master/frontend/src/components/MainLayout.jsx
import { useEffect } from 'react';
import { Navigate, Route, Routes } from 'react-router-dom';
import Sider from './Sider.jsx';
import SubAppContainer, { HomeRedirect } from './SubAppContainer.jsx';
import { useMenus } from '../hooks/useMenus.js';
import { registerSubApps } from '../qiankun/registerApps.js';

export default function MainLayout() {
  const { menus, rootMenus, loading, error } = useMenus();

  useEffect(() => {
    if (rootMenus.length > 0) {
      registerSubApps(rootMenus);
    }
  }, [rootMenus]);

  return (
    <div className="app-layout">
      <Sider menus={menus} loading={loading} error={error} />
      <main className="app-main">
        <Routes>
          <Route index element={<HomeRedirect rootMenus={rootMenus} />} />
          <Route path="/media/*" element={<SubAppContainer />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </main>
    </div>
  );
}

// menu-master/frontend/src/components/MainLayout.vue
<template>
  <el-container class="app-layout">
    <AppSider
      :menus="menus"
      :loading="loading"
      :error="error"
    />
    <el-container>
      <el-main class="app-content">
        <router-view />
      </el-main>
    </el-container>
  </el-container>
</template>

<script setup>
import { provide, watch } from 'vue';
import AppSider from './AppSider.vue';
import { useMenus } from '../composables/useMenus.js';
import { registerSubApps } from '../qiankun/registerApps.js';

const { menus, rootMenus, loading, error } = useMenus();

provide('rootMenus', rootMenus);

watch(rootMenus, roots => {
  if (roots.length > 0) {
    registerSubApps(roots);
  }
}, { immediate: true });
</script>
